<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Market\Module'                     => __DIR__ . '/Module.php',
    'Market\Controller\indexController' => __DIR__ . '/src/Market/Controller/indexController.php',
);
